server:
  port: 8089

spring:

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/article?useAffectedRows=true&useSSL=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource

    #配置阿里云数据库连接池

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
queue: articlequeue



#
redis:
  host: localhost
  port: 6379

  pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 2000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 10
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接超时时间（毫秒）
  timeout: 1000




mybatis:
  # 指定全局配置文件的位
  config-location: classpath:mybatis/mybatis-config.xml
  #指定sql映射文件的位
  mapper-locations: classpath:mybatis/mapper/*.xml
#图片上传之后读取路径的
cbs:
  imagesPath: file:/E:/fileUpload/
netty:
  proty: 8031
communication:
  sorecketlength:
logging:
  config: classpath:lockab.xml
  level:
    com:
      looedu:
        mapper: debug


